Alter Table PERSONNE
DROP FOREIGN KEY PERSONNE_CANDIDAT_FK;

Alter Table PERSONNE
ADD CONSTRAINT PERSONNE_CANDIDAT_FK
FOREIGN KEY (Num_Candidat) REFERENCES CANDIDAT(Num_Candidat);

Alter Table EQUIPE
DROP FOREIGN KEY EQUIPE_CANDIDAT_FK;

Alter Table EQUIPE
ADD CONSTRAINT EQUIPE_CANDIDAT_FK
FOREIGN KEY (Num_Candidat) REFERENCES CANDIDAT(Num_Candidat);

Alter Table CONSTITUER
DROP FOREIGN KEY CONSTITUER_CANDIDAT_FK,
DROP FOREIGN KEY CONSTITUER_COMPETITION0_FK;

Alter Table CONSTITUER
ADD CONSTRAINT CONSTITUER_CANDIDAT_FK
FOREIGN KEY (Num_Candidat) REFERENCES CANDIDAT(Num_Candidat),
ADD CONSTRAINT CONSTITUER_COMPETITION0_FK
FOREIGN KEY (Num_Competition) REFERENCES COMPETITION(Num_Competition);

Alter Table COMPOSER
DROP FOREIGN KEY composer_Personne_FK,
DROP FOREIGN KEY composer_Equipe0_FK;

Alter Table COMPOSER
ADD CONSTRAINT composer_Personne_FK 
FOREIGN KEY (Num_Candidat) REFERENCES Personne(Num_Candidat),
ADD CONSTRAINT composer_Equipe0_FK 
FOREIGN KEY (Num_candidat_Equipe) REFERENCES Equipe(Num_Candidat);

