Alter Table PERSONNE
DROP FOREIGN KEY PERSONNE_CANDIDAT_FK;

Alter Table PERSONNE
ADD CONSTRAINT PERSONNE_CANDIDAT_FK
FOREIGN KEY (num_candidat) REFERENCES CANDIDAT(num_candidat);

Alter Table EQUIPE
DROP FOREIGN KEY EQUIPE_CANDIDAT_FK;

Alter Table EQUIPE
ADD CONSTRAINT EQUIPE_CANDIDAT_FK
FOREIGN KEY (num_candidat) REFERENCES Candidat(num_candidat);


Alter Table CONSTITUER
DROP FOREIGN KEY CONSTITUER_CANDIDAT_FK,
DROP FOREIGN KEY CONSTITUER_COMPET_FK;

Alter Table CONSTITUER
ADD CONSTRAINT CONSTITUER_CANDIDAT_FK
FOREIGN KEY (num_candidat) REFERENCES Candidat(num_candidat),
ADD CONSTRAINT CONSTITUER_COMPET_FK
FOREIGN KEY (NumCompet) REFERENCES Competition(NumCompet);

Alter Table COMPOSER
DROP FOREIGN KEY composer_Personne_FK,
DROP FOREIGN KEY composer_Equipe0_FK;

Alter Table COMPOSER
ADD CONSTRAINT composer_Personne_FK 
FOREIGN KEY (num_candidat_Personne) REFERENCES Personne(num_candidat),
ADD CONSTRAINT composer_Equipe0_FK 
FOREIGN KEY (num_candidat_Equipe) REFERENCES Equipe(num_candidat);

